<div class="container mt-30">
    <div class="row">
        <?php echo $this->render('recruitment/common/menu.phtml');?>

        <div class="page_content col-xs-12 col-md-8">
            <?php if ($this->allRecruitmentData) { ?>
                <ul class="row page_content__lst">
                    <?php foreach ($this->allRecruitmentData as $data) { ?>
                        <?php
                        $title = $data[DbTable_Recruitment::COL_RECRUITMENT_TITLE];
                        $subContent = $data[DbTable_Recruitment::COL_RECRUITMENT_SUB_CONTENT];
                        $url = $this->recruitmentUrl($data[DbTable_Recruitment::COL_RECRUITMENT_ID], $title);
                        ?>
                        <li class="col-xs-12 col-sm-4">
                            <!--<a href=""><img src="images/demo.jpeg" class="img-responsive center-block"></a>-->
                            <p class="page_content__lst__title"><?php echo $title;?></p>
                            <p class="page_content__lst__cont"><?php echo $subContent;?></p>
                            <p class="page_content__lst__more">
                                <a href="<?php echo $url?>" title="<?php echo $title;?>"><?php echo $this->translate->_('common_detail');?> &gt;&gt;</a>
                            </p>
                        </li>
                    <?php } ?>
                </ul>
                <!--
                <nav aria-label="Page navigation" class="text-center">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                -->
            <?php } ?>
        </div>

    </div>
</div>