<?php echo $this->doctype(); ?>
<?php
$host =  Application_Function_Common::currentUrl();
$url = Application_Function_Common::fullCurrentUrl();
$imagePath = $this->banner[DbTable_Banner::COL_BANNER_IMAGE];
$thumbnail = null;
$mj = isset($_GET['xp']) ? $_GET['xp'] : '';
if (isset($this->metaImage) && $this->metaImage) {
    $imagePath = $this->metaImage;
}
if ($imagePath) {
    $thumbnail = $this->thumb($imagePath, 400);
    $thumbnail = $host . $thumbnail;
}
?>
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo isset($this->metaDescription) ? $this->metaDescription : $this->banner[DbTable_Banner::COL_BANNER_META_DESCRIPTION]; ?>">
    <meta name="keyword" content="<?php echo $this->banner[DbTable_Banner::COL_BANNER_META_KEYWORD];?>">
    <base href="/statics/asset/default/" />
    <link rel="canonical" href="<?php echo $url; ?>">
    <link rel="shortcut icon" type="image/png" href="/favicon.ico?m=<?php echo time();?>"/>
    <meta property="fb:app_id" content="1200581790010768" />
    <meta property="og:locale" content="en_US">
    <meta property="og:site_name" content="DaiNam" />
    <meta property="og:type" content="article" />
    <meta property="og:url" itemprop="url" content="<?php echo $url; ?>">
    <meta property="og:description" content="<?php echo isset($this->metaDescription) ? $this->metaDescription : $this->banner[DbTable_Banner::COL_BANNER_META_DESCRIPTION]; ?>">
    <meta property="og:title" content="<?php echo isset($this->metaTitle) ? $this->metaTitle : $this->banner[DbTable_Banner::COL_BANNER_META_TITLE]; ?>">
    <meta property="og:image" itemprop="thumbnailUrl" content="<?php echo $thumbnail; ?>">
    <!--
    <meta property="fb:admins" content="zzzzzzzzzz">-->
    <title><?php echo isset($this->metaTitle) ? $this->metaTitle : $this->banner[DbTable_Banner::COL_BANNER_META_TITLE]; ?></title>
    <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Arapey:400,400italic' rel='stylesheet' type='text/css'>
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/jquery.bxslider.css" rel="stylesheet">
    <link href="css/utils.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style-dulich.css" rel="stylesheet">
    <link href="css/jquery-ui.css" rel="stylesheet">
    <link href="autoload/css/common.css" rel="stylesheet">
    <?php echo $this->headLink(); ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-57088078-4', 'auto');
    ga('send', 'pageview');

</script>
<div class="wrapper" id="panel">
    <header class="header-full fixed">
        <div class="header">
            <div class="container">
                <div class="row h_top">
                    <div class="col-xs-10 col-sm-1">
                        <a href="/" class="h_nav_logo">
                            <img src="images/h_logo.png" class="img-responsive center-block">
                        </a>
                    </div>
                    <div class="col-xs-2 hidden-lg hidden-sm hidden-md">
                        <button type="button" class="navbar-toggle h_nav_btn">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="col-xs-11">
                        <div class="h_nav clearfix" id="menu">
                            <ul>
                                <li>
                                    <div class="hidden-md hidden-lg text-right pt10 pb10">
                                        <a href="/vi" class="block_inline pl10"><img src="images/flag_vi.png"> </a>
                                        <a href="/en" class="block_inline pl10"><img src="images/flag_us.png"> </a>
                                    </div>
                                </li>
                                <li>
                                    <a href="/"><?php echo $this->translate->_('admin_resource_homepage');?></a>
                                </li>
                                <li><!-- class="active"-->
                                    <a href="<?php echo $this->configUrl($this->config, 'about_us');?>">
                                        <?php echo $this->translate->_('admin_resource_about_us');?>
                                    </a>
                                    <?php if (isset($this->menuAboutUsCategory)) { ?>
                                    <ul class="h_nav_link">
                                        <?php foreach ($this->menuAboutUsCategory as $category) { ?>
                                            <?php
                                            $name = $category[DbTable_About_Us_Category::COL_ABOUT_US_CATEGORY_NAME];
                                            $id = $category[DbTable_About_Us_Category::COL_ABOUT_US_CATEGORY_ID];
                                            $url = $this->aboutUsCategoryUrl($id, $name);
                                            $subData = isset($category['sub']) ? $category['sub'] : null;
                                            ?>
                                            <li>
                                                <a href="<?php echo $url;?>" title="<?php echo $name;?>"><?php echo $name;?></a>
                                                <?php if ($subData) { ?>
                                                    <ul>
                                                        <?php foreach ($subData as $sub) { ?>
                                                            <?php
                                                            $subName = $sub[DbTable_About_Us_Sub_Category::COL_ABOUT_US_SUB_CATEGORY_NAME];
                                                            $subUrl = $this->aboutUsSubCategoryUrl(
                                                                $id,
                                                                $name,
                                                                $sub[DbTable_About_Us_Sub_Category::COL_ABOUT_US_SUB_CATEGORY_ID],
                                                                $subName
                                                            );
                                                            ?>
                                                            <li><a href="<?php echo $subUrl;?>" title="<?php echo $subName;?>"><?php echo $subName;?></a></li>
                                                        <?php } ?>
                                                    </ul>
                                                <?php } ?>
                                            </li>
                                        <?php } ?>
                                        <!--
                                        <li><a href="<?php echo $this->configUrl($this->config, 'horse');?>" style="text-transform: uppercase"><?php echo $this->translate->_('admin_privilege_horse');?></a> </li>-->
                                    </ul>
                                    <?php } ?>
                                </li>

                                <li>
                                    <a href="<?php echo $this->configUrl($this->config, 'schedule');?>">
                                        <?php echo $this->translate->_('admin_resource_schedule');?></a>
                                    <?php if (isset($this->menuServiceCategory)) { ?>
                                        <ul class="h_nav_link">
                                            <?php foreach ($this->menuScheduleCategory as $category) { ?>
                                                <?php
                                                $name = $category[DbTable_Schedule_Category::COL_SCHEDULE_CATEGORY_NAME];
                                                $id = $category[DbTable_Schedule_Category::COL_SCHEDULE_CATEGORY_ID];
                                                $url = $this->scheduleCategoryUrl($id, $name);
                                                ?>
                                                <li><a href="<?php echo $url;?>" title="<?php echo $name;?>"><?php echo $name;?></a></li>
                                            <?php } ?>
                                        </ul>
                                    <?php } ?>
                                </li>
                                <li>
                                    <a href="<?php echo $this->configUrl($this->config, 'report');?>">
                                        <?php echo $this->translate->_('admin_resource_report');?>
                                    </a>
                                    <?php if (isset($this->menuReportCategory)) { ?>
                                        <ul class="h_nav_link">
                                            <?php foreach ($this->menuReportCategory as $data) { ?>
                                                <?php
                                                $id = $data[DbTable_Report_Category::COL_REPORT_CATEGORY_ID];
                                                $name = $data[DbTable_Report_Category::COL_REPORT_CATEGORY_NAME];
                                                ?>
                                                <li>
                                                    <a href="<?php echo $this->reportCategoryUrl($id, $name);?>" title="<?php echo $name;?>"><?php echo $name;?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    <?php } ?>
                                </li>
                                <!--
                                <li>
                                    <a href="">Tường thuật các vòng đua</a>
                                </li> -->
                                <li>
                                    <a href="<?php echo $this->configUrl($this->config, 'service');?>">
                                        <?php echo $this->translate->_('admin_resource_service');?>
                                    </a>
                                    <?php if (isset($this->menuServiceCategory)) { ?>
                                        <ul class="h_nav_link">
                                            <?php foreach ($this->menuServiceCategory as $category) { ?>
                                                <?php
                                                $name = $category[DbTable_Service_Category::COL_SERVICE_CATEGORY_NAME];
                                                $id = $category[DbTable_Service_Category::COL_SERVICE_CATEGORY_ID];
                                                $url = $this->serviceCategoryUrl($id, $name);
                                                ?>
                                                <li><a href="<?php echo $url;?>" title="<?php echo $name;?>"><?php echo $name;?></a></li>
                                            <?php } ?>
                                        </ul>
                                    <?php } ?>
                                </li>
                                <li class="h_lst_btn">
                                    <a href="<?php echo $this->configUrl($this->config, 'ticket_online');?>" class="h-btn"><?php echo $this->translate->_('admin_resource_ticket_online');?></a>
                                    <ul class="h_nav_link">
                                        <li><a href="<?php echo $this->configUrl($this->config, 'ticket_online_introduction');?>"><?php echo $this->translate->_('admin_privilege_ticket_online_introduction');?></a></li>
                                        <li><a href="<?php echo $this->configUrl($this->config, 'ticket_online_system');?>"><?php echo $this->translate->_('admin_privilege_ticket_online_rule');?></a></li>
                                    </ul>
                                </li>
                                <li class="h_lst_last">
                                    <div class="hidden-xs hidden-sm">
                                        <a href="/vi"><img src="images/flag_vi.png"> </a>
                                        <a href="/en"><img src="images/flag_us.png"> </a>
                                    </div>
                                    <a href="<?php echo $this->configUrl($this->config, 'recruitment');?>">
                                        <?php echo $this->translate->_('admin_resource_recruitment');?>
                                    </a>
                                    <ul class="h_nav_link">
                                        <li><a href="<?php echo $this->configUrl($this->config, 'recruitment_hr_benefit');?>"><?php echo $this->translate->_('admin_privilege_hr_benefit');?></a></li>
                                        <li><a href="<?php echo $this->configUrl($this->config, 'recruitment');?>"><?php echo $this->translate->_('admin_privilege_recruitment');?></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="main-full">
        <div class="main">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>

    <footer class="footer-full">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-9">
                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <p class="f_nav_title"><?php echo $this->translate->_('admin_resource_schedule');?></p>
                                <ul class="f_nav_link">
                                    <li>
                                        <a href="<?php echo $this->configUrl($this->config, 'schedule');?>">
                                            <?php echo $this->translate->_('admin_resource_schedule');?></a>
                                    </li>
                                    <li>
                                        <?php
                                        $id = $this->newsEventCategoryInfo[DbTable_News_Category::COL_NEWS_CATEGORY_ID];
                                        $name = $this->newsEventCategoryInfo[DbTable_News_Category::COL_NEWS_CATEGORY_NAME];
                                        ?>
                                        <a href="<?php echo $this->newsCategoryUrl($id, $name);?>"><?php echo $this->translate->_('layout_event_coming');?></a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->configUrl($this->config, 'souvenir');?>">
                                            <?php echo $this->translate->_('admin_resource_souvenir');?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <!--
                                <p class="f_nav_title">KẾT QUẢ CÁC TRẬN ĐUA</p>
                                <ul class="f_nav_link">
                                    <li><a href="">KẾT QUẢ ĐUA NGỰA NGÀY 18/10/2016</a> </li>
                                    <li><a href="">KẾT QUẢ ĐUA CHÓ NGÀY 20/10/2016</a> </li>
                                    <li><a href="">KẾT QUẢ ĐUA MOTO NGÀY 20/10/2016</a> </li>
                                </ul>-->
                                <p class="f_nav_title"><?php echo $this->translate->_('admin_resource_news');?></p>
                                <ul class="f_nav_link">
                                    <?php foreach ($this->menuNewsCategory as $data) { ?>
                                        <?php
                                        $id = $data[DbTable_News_Category::COL_NEWS_CATEGORY_ID];
                                        $name = $data[DbTable_News_Category::COL_NEWS_CATEGORY_NAME];
                                        ?>
                                        <li>
                                            <a href="<?php echo $this->newsCategoryUrl($id, $name);?>" title="<?php echo $name;?>"><?php echo $name;?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <p class="f_nav_title"><?php echo $this->translate->_('admin_resource_member');?></p>
                                <ul class="f_nav_link">
                                    <?php foreach ($this->menuMemberCategory as $data) { ?>
                                        <?php
                                        $id = $data[DbTable_Member_Category::COL_MEMBER_CATEGORY_ID];
                                        $name = $data[DbTable_Member_Category::COL_MEMBER_CATEGORY_NAME];
                                        ?>
                                        <li>
                                            <a href="<?php echo $this->memberCategoryUrl($id, $name);?>" title="<?php echo $name;?>"><?php echo $name;?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <p class="f_nav_title"><?php echo $this->translate->_('admin_resource_contact');?></p>
                                <p class="w_color"><?php echo $this->contactInformation[DbTable_Content::COL_CONTENT_CONTENT];?></p>
                                <p class="mt05">
                                    <a target="_blank" href="<?php echo $this->config->social->facebook->host;?>"><img src="images/icons/fb.png"></a>
                                    <a target="_blank" href="<?php echo $this->config->social->youtube->host;?>"><img src="images/icons/youtube.png"></a>
                                </p>
                            </div>
                        </div>
                        <p class="fs12 g_color mt15">COPYRIGHT 2016 - CONG TY CO PHAN DAI NAM - ALLRIGHT RESERVED  -  DESIGNED by SAVEMONEY</p>
                    </div>
                    <div class="col-xs-12 col-sm-3">
                        <img src="images/map.jpg" class="img-responsive center-block">
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<script src="js/jquery-1.12.4.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script src="js/modernizr-3.3.1.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/slideout.min.js"></script>
<script src="js/jquery.fitvids.js"></script>
<script src="js/jquery.bxslider.min.js"></script>
<script src="js/common.js"></script>
<script src="autoload/js/common.js"></script>
<?php echo $this->headScript(); ?>
</body>
</html>