<div class="container mt-30">
    <div class="row">
        <?php echo $this->render('footer/common/menu.phtml');?>
        <div class="page_content col-xs-12 col-md-8">
            <div class="detail__title"><?php echo $this->info[DbTable_Content::COL_CONTENT_TITLE];?></div>
            <div class="detail__content">
                <?php echo $this->info[DbTable_Content::COL_CONTENT_CONTENT];?>
            </div>
        </div>
    </div>
</div>