<div class="container mt-30">
    <div class="row">
        <?php echo $this->render('value/common/menu.phtml');?>
        <div class="page_content col-xs-12 col-md-8">
            <div class="detail__title"><?php echo $this->title;?></div>
            <div class="detail__content">
                <?php echo $this->content;?>
            </div>
            <?php echo $this->render('layout/add-this.phtml');?>
        </div>
    </div>
</div>